AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - 'sorbet/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false